discord:
  token: NTY2MDIyOTk0NTQ0MDMzODIy.XUHdeA.hhe3RQx4KZMgQ-lW7LElqJ5hAV0
MySQL:
  host: 24.239.87.182
  database: s108_database
  port: 3306
  username: u108_9lZRY9hbQa
  password: 5LZP682yu5Yho2GJMzLm
